# Generated by Django 2.2.5 on 2019-12-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191212_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skladnik',
            old_name='pizza',
            new_name='pizze',
        ),
    ]
